SCREEN 12
CLS
PRINT
PRINT "                                          DGG                                   "
PRINT "                                         EGDGG                                  "
PRINT "    Cat333Pok‚mon presents:             GG;tG                                  "
PRINT "                                       GG,,,GG                                 "
PRINT "                             DGGEG.    GG,,GG        GGGGG                      "
PRINT "         GGGGGGGGG        GGGGGGGGGL  EGGGG     GGGGGGGGGG                      "
PRINT "      GGGGtttttttGG     EGGLt,tGG,tGG EGGGGGGG EGGtttG;,tG    EKGGGG            "
PRINT "     GGG,,,,,,,,,tGG    DG,,,,tGG,,tGGGGtttttGGEG,,,tG,,tG    DEGtGGGGGG        "
PRINT "   EGG,,,,,,,,,,,,tGG   DGGG,,tG,,,,tGG,,,,,,tGGG,,,;G,,,GG   DDG,,,tGGGGGGG    "
PRINT "   EGG,,,,,,,,,,,,,tG   DDGG,,t,,,,,GG,,LLLG,,GGG,,,,G,,,GG   DEGG,,,tGGtttGG   "
PRINT "   DEGG,,,,,,tLLL,,tG    EEG,,,,,,,GG;,tL G,,GGEG,,,,t,,,tGGGGGGGG,,,tGG,,,GG   "
PRINT "    DDG,i,,,,tL G;,tGGGGGGGG,,,,,,GGG,,t G,;GGGGG,,,,,,,,tGGt,;tGG,,,tGD,,,G    "
PRINT "     DGGG;,,,,G G;,GGG,,,ttG;,,,,GG G,,tG,,GGtGGG,,,,,,,,GG,L,,,tGG,,tG,,,tG    "
PRINT "     DDGGG,,,,tLG,,GG,GL,,,tG,,,itGGGG,,,,t,,,tLGj,t,,,,tG,tL,,t,tG,,,G,,,GG    "
PRINT "      DDDG,,,,tL,,GG,,LL,,;tG,,,,,,ttG,,,,,,,,GGL,,G,,t,GG,tGGGG,tG,,,t,,,G     "
PRINT "        EGG,,,,,,GGG,iGGGG,,G,,G,,,,tLGL,,,,LGGG,,,GG,G,G,,itGL,,tG,,,,,,tG     "
PRINT "        EEG,,,,,GGG,,,tLGi,,G,,GGG;,,ttGGGGGGGGG,,,GG,G,GG,,,,,,,Gjt,,,,,GD     "
PRINT "         EGG,,,tGDGG,,,,,,,tG,,GEGGG,,,ttGGE KGG,,tGGGG,tG,,,,,,DG,t,,,,,G      "
PRINT "         EEG,,,tGGDG,,,,,,,GG,,G EEGGG;,,GG  KGGGGGGGGGLtGG,,,,GG,,i,,,,tG      "
PRINT "          KGG,,,GGEGG,,,,,GGG,,G   EEGGG;GG    EEEEEEGGG,tGGGGGGG,,G,,,,GG      "
PRINT "          KEG,,,tGEEGGGGGGGGGGGG     EEGGGG         EEGGGGGGEEKGG,,G,,,,G       "
PRINT "          KKGf,,tG EEEGGE DDGGGG       EEGf          EEEDGGGG KGGGGGi,,tG       "
PRINT "           KGG,,tGL       DG             E               KKK   EEEEGf,,GG       "
PRINT "           KKG,fGGG                                               KGGG,G        "
PRINT "            KGGGGK               Black and White                  KKKGGG        "
PRINT "            KKE                Wild Pok‚mon Battle                   EK  KW     "
PRINT "                                                                         K"

'END

PLAY "T190O3L16"
'GOTO LOOPSONG
PLAY "B-AA-AA-GA-GF+GF+FF+FEF"
PLAY "EE-EE-DE-DC+DC+CC+C<B>C<B>"
PLAY "GP4P16D+P4P16GP8P16FP4P16D+P8P16GP4P16"
PLAY "L2C>C<L4C.>L3C....<"
PLAY "L16GP4P16>C<P4P16GP8P16>D+P4P16C+P8P16L4C.<"
PLAY "L2D+>D+<L4G.>L3G....<"
LOOPSONG:  
PLAY "L4C.F.GB-.AL8GFP8L2E-.L16G.P32P8"
PLAY "L8E-GP8L3B-...L4A.G.L16FP16P8"
PLAY "L4B-.A.L16GP16P8"
PLAY "L2>E-D<L4G.B-.GL1AL2>C.L16<FGB->C"
PLAY "L2E-FL4E-.D.<B->L2C..L16E-EL1F"

PLAY "L16<E-P16FP8P16L3G...L4B-.L16AA-L2G"
PLAY "L16FP16GP8P16L4A.F>C.<L16BB-L2A"
PLAY "L16GP16AP8P16L4B-.G>E-.D.<B-"
PLAY "L2A..L16B-B>L1C"

PLAY "L16<E-P16FP8P16L3G...L4B-.L16AA-L2G"
PLAY "L16FP16GP8P16L4A.F>C.<L16BB-L2A"
PLAY "L16GP16AP8P16L4B-.G>E-DC<B->L2C..L16E-EL2F..L8G"

PLAY "L1G+...L8GL1F...L8GL1G+...L8AT95L1B-T190"
PLAY "L1D<B-"
GOTO LOOPSONG

