SCREEN 7
CLS
COLOR 9, 0
CLS
PRINT "ЙННННННННННННННННННННННННННННННННННННН»"
PRINT "єPok‚mon Diamond/Pearl: Trainer Battleє"
PRINT "ЗДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДД¶"
PRINT "є          By Cat333Pok‚mon           є"
PRINT "ЗДДДДДДВДДДДДДДДДДДДДДДДДДВДДДДДДДДДДД¶"
PRINT "єQBasicі 13 November 2007 іNintendo DSє"
PRINT "ИННННННПННННННННННННННННННПНННННННННННј"
COLOR 15
PRINT " C 1995-2007 NINTENDO, POKђMON,"
PRINT "             GAME FREAK, CREATURES"
PRINT : PRINT "Press a key to begin!"
CIRCLE (11, 59), 7

SLEEP
COLOR 15, 0
CLS

'Initial Settings
PLAY "T185O4L16"

INTRO:
'Introduction
PRINT "ЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫ"
PLAY "C<"
PRINT "ЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫ"
PLAY "B"
PRINT "ЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫ"
PLAY "B-"
PRINT "ЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫ"
PLAY "A"
PRINT "ЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫ"
PLAY "B-"
PRINT "ЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫ"
PLAY "A"
PRINT "ЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫ"
PLAY "G+"
PRINT "ЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫ"
PLAY "G"
PRINT "ЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫ"
PLAY "G+"
PRINT "ЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫ"
PLAY "G"
PRINT "ЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫ"
PLAY "F+"
CLS
PLAY "F"
COLOR 1, 0
CLS
PLAY "F+"
COLOR 1, 15
CLS
PLAY "F"
COLOR 1, 0
CLS
PLAY "E"
COLOR 1, 15
CLS
PLAY "E-"
COLOR 1, 0
CLS
PLAY "E"
COLOR 1, 15
CLS
PLAY "E-"
COLOR 1, 0
CLS
PLAY "D"
COLOR 1, 15
CLS
PLAY "C+"
COLOR 1, 0
CLS
PLAY "D"
COLOR 1, 15
CLS
PLAY "C+"
COLOR 1, 0
CLS
PLAY "C"
COLOR 1, 15
CLS
PLAY "<B>"
COLOR 1, 0
CLS
PLAY "C"
COLOR 1, 15
CLS
PLAY "<B"
COLOR 1, 0
CLS
PLAY "B-"
COLOR 1, 15
CLS
PLAY "A"
COLOR 1, 0
CLS
PLAY "B-"
COLOR 1, 15
CLS
PLAY "A"
COLOR 1, 0
CLS
PLAY "G+"
COLOR 1, 15
CLS
PLAY "G"
COLOR 0, 0
CLS

BRASS:
'Brass section
COLOR 15

PRINT "ЙННННННННННННННННННННННННННННННННННННН»"
PRINT "є                                     є"
PRINT "є                                     є"
PRINT "є                                     є"
PRINT "є                                     є"
PRINT "є                                     є"
PRINT "є                                     є"
PRINT "є                                     є"
PRINT "є                                     є"
PRINT "є                                     є"
PRINT "є                                     є"
PRINT "є                                     є"
PRINT "є                                     є"
PRINT "є                                     є"
PRINT "є                                     є"
PRINT "є                                     є"
PRINT "є                                     є"
PRINT "є                                     є"
PRINT "єЪДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДїє"
PRINT "єі                                   іє"
PRINT "єі                                   іє"
PRINT "єАДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДДЩє"
PRINT "ИНННННННННННННННННННННННННННННННННННННј"

'PRINT "Pok‚ Trainer Bob would like to battle!"
LOCATE 20, 3: PRINT "Pok‚ Trainer Bob"
LOCATE 21, 3: PRINT "would like to battle!"

PLAY "L8CP4CP4CP8CP3CL4C+."
LOCATE 2, 2: PRINT "ЪДДДДДДДДДДДДДДї"
LOCATE 3, 2: PRINT "іBUIZEL     L15і"
LOCATE 4, 2: PRINT "і   HP         і"
COLOR 2
LOCATE 4, 8: PRINT "ЮЫЫЫЫЫЫЫЭ"
COLOR 15
LOCATE 5, 2: PRINT "АДДДДДДДДДДДДДДЩ"
LOCATE 20, 3: PRINT "Bob sent out BUIZEL!     "
LOCATE 21, 3: PRINT "                         "
PLAY "L8CP4CP4CP8CP3CL4C+."
LOCATE 15, 23: PRINT "ЪДДДДДДДДДДДДДДї"
LOCATE 16, 23: PRINT "іTURTWIG    L13і"
LOCATE 17, 23: PRINT "і   HP         і"
COLOR 2
LOCATE 17, 29: PRINT "ЮЫЫЫЫЫЫЫЭ"
COLOR 15
LOCATE 18, 23: PRINT "АДДДДДДДДДДДДДДЩ"
LOCATE 20, 3: PRINT "Go, TURTWIG!        "
PLAY "L8GP4GP4GP8GP3GL4G+."
COLOR 9
LOCATE 20, 3: PRINT "BUIZEL used Water Gun."
LOCATE 21, 3: PRINT "It's not very effective."
LOCATE 17, 37: PRINT " "
PLAY "L8GP4GP4GP8GP3GL4G+."
COLOR 2
LOCATE 20, 3: PRINT "TURTWIG used Razor Leaf."
LOCATE 21, 3: PRINT "It's super effective!   "
COLOR 2
LOCATE 4, 14: PRINT "Э  "

HORN1:                                   
'French horn
PLAY "O2L4C.G.L4>C<B-G+"
COLOR 3
LOCATE 20, 3: PRINT "BUIZEL used Ice Beam.   "
LOCATE 21, 3: PRINT "It's super effective!"
COLOR 14
LOCATE 17, 29: PRINT "ЮЫЫЫЭ   "
COLOR 15
PLAY "GFL16EP8FL2GL4>DL1<B-"
LOCATE 20, 3: PRINT "TURTWIG used Tackle. "
LOCATE 21, 3: PRINT "                     "
COLOR 2
LOCATE 4, 13: PRINT "Э "
PLAY "L4C.G.L4>C<B-G+GFL16EP8FL2GL16>CP8DL2ED<"
PLAY "L8E.L16CL4CL8G.L16EL4EL8>C.<L16GL2GP4"
PLAY "L8F.L16DL4DL8B-.L16FL4FL8>D.<L16B-L2B-L4B"
PLAY ">L2C.<L4G>L2E.L4CL2G.L8FP16L16E-L1E"

TRUMPET:
'Muted trumpet
PLAY "L2GL8FEDCL2DP2EL8GFEDL2EP2L8F.E.FG+GFE-G+GFE-FGG+B-GG+B->C<B-G+GF"
PLAY "L4GL8FGB-G+GB-L1AB-L2>C.<L4B-L1A"

TIMPANI:
'Brass + Timpani
PLAY "L1O3GO1L16C<P16GP16GP16>C<P16GP16GP16>C<P16GP16"
PLAY "L1O3G+O1L16C+<P16G+P16G+P16>C+<P16G+P16G+P16>C+<P16G+P16"
PLAY "L1O3FO0L16B-P16FP16FP16B-P16FP16FP16B-P16FP16"
PLAY "L1O3G+O1L16C+<P16G+P16G+P16>C+<P16G+P16G+P16>C+<P16G+P16"
PLAY "L1O3GO1L16C<P16GP16GP16>C<P16GP16GP16>C<P16GP16"
PLAY "L1O3G+O1L16C+<P16G+P16G+P16>C+<P16G+P16G+P16>C+<P16G+P16"
PLAY "L1O3B-O1L16E-<P16B-P16B-P16>E-<P16B-P16B-P16>E-<P16B-P16"
PLAY "L1O4C+O1L16F+P16C+P16C+P16F+P16C+P16C+P16F+P16C+P16"

HORN2:
'French horn
PLAY "O4L4C.C+L8C<B->C+L4C.C+L8C<B->C+L4C.C+L8C<B->C+L4C.C+L8C<B->C+"
PLAY "O3L4C.C+L8C<B->C+L4C.C+L8C<B->C+L4C.C+L8C<B->C+L4C.C+L8C<B->C+"
PLAY "O2L4C.C+L8C<B->C+L4C.C+L8C<B->C+L4C.C+L8C<B->C+CC+E-FF+CC+<B-"

SQUARE:
'Square wave
PLAY "O1L8CFG+GCGC+FCFG+GCGC+FCFG+GCGC+FCFG+GCGC+F"
PLAY "CFG+GCGC+FCFG+GCGC+FCFG+GCGC+FCFG+GCGC+F"

'GOTO HORN1