DECLARE SUB BIGLINE (ENDTYPE AS INTEGER)
DECLARE SUB LYRIC (VAR AS STRING, VARCOLOR AS INTEGER)
CLS
PRINT "                                 Winter Wrap Up"
PRINT "                       My Little Pony: Friendship is Magic": PRINT

COLOR 5
PRINT "                       Twilight Sparkle       ";
COLOR 11
PRINT "Rainbow Dash"
COLOR 13
PRINT "                       Pinkie Pie             ";
COLOR 6
PRINT "   Applejack"
COLOR 15
PRINT "                       Rarity                 ";
COLOR 14
PRINT "  Fluttershy"
COLOR 10
PRINT "                                    Everypony"
PRINT

BIGLINE 1
LYRIC "VERSE 1", 7
BIGLINE 3
PLAY "MBT192O3L4"

'GOTO Twi

PLAY "MF": PLAY "MBC+C+D+FC+D+L2D+L4"
LYRIC "Three months of winter coolness", 11
PLAY "MF": PLAY "MBC+G+G+L8G+L4B-.L2G+P4"
LYRIC "And awesome holidays", 11

PLAY "MF": PLAY "MBL4C+FFFG+L8G+L4FE-."
LYRIC "We've kept our hoovesies warm at home", 13
PLAY "MF": PLAY "MBC+FL8FL4FF+.L2C+P4"
LYRIC "Time off from work to play", 13

PLAY "MF": PLAY "MB<L8B->CL4C+C+C+FL8E-L4C+.C+"
LYRIC "But the food we've stored is running out", 6
PLAY "MF": PLAY "MBL8C+E-L4FFL8FL4F+.L2E-P4"
LYRIC "We can't grow in this cold", 6

PLAY "MF": PLAY "MBL4F+G+G+G+G+G+FE-"
LYRIC "And even though I love my boots", 15
PLAY "MF": PLAY "MBC+E-C+L8E-L4F.T224L1E-P4P2"
LYRIC "This fashion's getting old", 15

PLAY "MF": PLAY "MBT112L8C+G+G+G+FG+L4B-G+"
LYRIC "The time has come to welcome spring", 5
PLAY "MF": PLAY "MBL8C+L16E-L8F.F+FC+"
LYRIC "And all things warm and green", 5
PLAY "MF": PLAY "MBL16FF+L8G+G+G+G+L4G+L8FL4G+"
LYRIC "But it's also time to say good-bye", 5
PLAY "MF": PLAY "MBL8C+L16E-L8F.F+FL4C+P8"
LYRIC "It's winter we must clean", 5
PLAY "MF": PLAY "MBL16C+L8E-F.E-L16C+L8E-F.L4C+"
LYRIC "How can I help? I'm new, you see", 5
PLAY "MF": PLAY "MBL16FFFFL8F+L16FL4C+P8"
LYRIC "What does everypony do?", 5
PLAY "MF": PLAY "MBL8C+L16E-L8F.E-C+L16E-L8F.FC+P8"
LYRIC "How do I fit in without magic?", 5
PLAY "MF": PLAY "MBC+G+G+L16G+L8B-.L2G+P2"
LYRIC "I haven't got a clue", 5

BIGLINE 2
LYRIC "CHORUS", 7
BIGLINE 3

COLOR 7
PRINT "             º ";
COLOR 10
PLAY "MF"
PRINT "Win";
'PLAY "T116L8C+C+FC+F+F+B-G+"
PLAY "T116MLL64<G+>C+<G+>C+<G+>C+<G+P64"
PRINT "ter ";
PLAY "G+>C+<G+>C+<G+>C+<G+P64"
PRINT "Wrap-";
PLAY ">C+FC+FC+FC+<P64"
PRINT "Up";
PLAY "G+>C+<G+>C+<G+>C+<G+P64"
COLOR 7
PRINT "                                      º "
PRINT "             º ";
COLOR 10
'LYRIC "Winter Wrap-Up", 10
PRINT "Win";
PLAY ">C+F+C+F+C+F+C+P64"
PRINT "ter ";
PLAY "C+F+C+F+C+F+C+P64"
PRINT "Wrap-";
PLAY "F+B-F+B-F+B-F+P64"
PRINT "Up";
PLAY "E-G+E-G+E-G+P64P8"
'LYRIC "Winter Wrap-Up", 10
COLOR 7
PRINT "                                      º "
PLAY "MBMNL8G+L16G+G+L8FG+L16FL8E-.C+"
LYRIC "Let's finish our holiday cheer", 10
COLOR 7
PRINT "             º ";
COLOR 10
PLAY "MF"
PRINT "Win";
'PLAY "T116L8C+C+FC+F+F+B-G+"
PLAY "T116MLL64<G+>C+<G+>C+<G+>C+<G+P64"
PRINT "ter ";
PLAY "G+>C+<G+>C+<G+>C+<G+P64"
PRINT "Wrap-";
PLAY ">C+FC+FC+FC+<P64"
PRINT "Up";
PLAY "G+>C+<G+>C+<G+>C+<G+P64"
COLOR 7
PRINT "                                      º "
PRINT "             º ";
COLOR 10
'LYRIC "Winter Wrap-Up", 10
PRINT "Win";
PLAY ">C+F+C+F+C+F+C+P64"
PRINT "ter ";
PLAY "C+F+C+F+C+F+C+P64"
PRINT "Wrap-";
PLAY "F+B-F+B-F+B-F+P64"
PRINT "Up";
PLAY "E-G+E-G+E-G+P64P8"
'LYRIC "Winter Wrap-Up", 10
COLOR 7
PRINT "                                      º "
PLAY "MBMNL16G+G+L8G+FG+L4B-G+"
LYRIC "'Cause tomorrow spring is here", 10
PLAY "L16G+G+L8G+FG+FL4C+"
LYRIC "'Cause tomorrow spring is here", 10

BIGLINE 2
LYRIC "VERSE 2", 7
BIGLINE 3

PLAY "MF": PLAY "MBL8G+G+G+FG+L4B-G+"
LYRIC "Bringing home the southern birds", 11
PLAY "MF": PLAY "MBL8C+L16E-FL8FF+FC+"
LYRIC "A Pegasus' job begins", 11
PLAY "MF": PLAY "MBFG+G+G+G+L4G+L8FL4G+"
LYRIC "And clearing all the gloomy skies", 11
PLAY "MF": PLAY "MBL16C+L8E-F.F+FL4C+P8"
LYRIC "And let the sun shine in", 11
PLAY "MF": PLAY "MBL16C+L8E-F.E-C+"
LYRIC "We move the clouds", 11
PLAY "MF": PLAY "MBC+C+G+.G+.B-.L4G+P16P4"
LYRIC "And we melt the white snow", 11
PLAY "MF": PLAY "MBL16C+C+L8FFE-C+"
LYRIC "When the sun comes up", 11
PLAY "MF": PLAY "MBC+C+G+.G+.L4B-L1G+"
LYRIC "Its warmth and beauty will glow", 11

'Twi:
BIGLINE 2
LYRIC "CHORUS", 7
BIGLINE 3

COLOR 7
PRINT "             º ";
COLOR 10
PLAY "MF"
PRINT "Win";
'PLAY "T116L8C+C+FC+F+F+B-G+"
PLAY "T116MLL64<G+>C+<G+>C+<G+>C+<G+P64"
PRINT "ter ";
PLAY "G+>C+<G+>C+<G+>C+<G+P64"
PRINT "Wrap-";
PLAY ">C+FC+FC+FC+<P64"
PRINT "Up";
PLAY "G+>C+<G+>C+<G+>C+<G+P64"
COLOR 7
PRINT "                                      º "
PRINT "             º ";
COLOR 10
'LYRIC "Winter Wrap-Up", 10
PRINT "Win";
PLAY ">C+F+C+F+C+F+C+P64"
PRINT "ter ";
PLAY "C+F+C+F+C+F+C+P64"
PRINT "Wrap-";
PLAY "F+B-F+B-F+B-F+P64"
PRINT "Up";
PLAY "E-G+E-G+E-G+P64P8"
'LYRIC "Winter Wrap-Up", 10
COLOR 7
PRINT "                                      º "
PLAY "MBMNL8G+L16G+G+L8FG+L16FL8E-.C+"
LYRIC "Let's finish our holiday cheer", 10
COLOR 7
PRINT "             º ";
COLOR 10
PLAY "MF"
PRINT "Win";
'PLAY "T116L8C+C+FC+F+F+B-G+"
PLAY "T116MLL64<G+>C+<G+>C+<G+>C+<G+P64"
PRINT "ter ";
PLAY "G+>C+<G+>C+<G+>C+<G+P64"
PRINT "Wrap-";
PLAY ">C+FC+FC+FC+<P64"
PRINT "Up";
PLAY "G+>C+<G+>C+<G+>C+<G+P64"
COLOR 7
PRINT "                                      º "
PRINT "             º ";
COLOR 10
'LYRIC "Winter Wrap-Up", 10
PRINT "Win";
PLAY ">C+F+C+F+C+F+C+P64"
PRINT "ter ";
PLAY "C+F+C+F+C+F+C+P64"
PRINT "Wrap-";
PLAY "F+B-F+B-F+B-F+P64"
PRINT "Up";
PLAY "E-G+E-G+E-G+P64P8"
'LYRIC "Winter Wrap-Up", 10
COLOR 7
PRINT "                                      º "
PLAY "MBMNL16G+G+L8G+FG+L4B-L8G+"
LYRIC "'Cause tomorrow spring is here", 10
COLOR 7
PRINT "             º ";
COLOR 10
PLAY "MF"
PRINT "Win";
'PLAY "T116L8C+C+FC+F+F+B-G+"
PLAY "T116MLL64<G+>C+<G+>C+<G+>C+<G+P64"
PRINT "ter ";
PLAY "G+>C+<G+>C+<G+>C+<G+P64"
PRINT "Wrap-";
PLAY ">C+FC+FC+FC+<P64"
PRINT "Up";
PLAY "G+>C+<G+>C+<G+>C+<G+P64"
COLOR 7
PRINT "                                      º "
PRINT "             º ";
COLOR 10
'LYRIC "Winter Wrap-Up", 10
PRINT "Win";
PLAY ">C+F+C+F+C+F+C+P64"
PRINT "ter ";
PLAY "C+F+C+F+C+F+C+P64"
PRINT "Wrap-";
PLAY "F+B-F+B-F+B-F+P64"
PRINT "Up";
PLAY "E-G+E-G+E-G+P64P8"
'LYRIC "Winter Wrap-Up", 10
COLOR 7
PRINT "                                      º "
PLAY "MBMNL16G+G+L8G+FG+L4B-G+"
LYRIC "'Cause tomorrow spring is here", 10
PLAY "L16G+G+L8G+FG+FL4C+"
LYRIC "'Cause tomorrow spring is here", 10

BIGLINE 2
LYRIC "VERSE 3", 7
BIGLINE 3

PLAY "MF": PLAY "MBL8G+G+G+FG+L4B-G+"
LYRIC "Little critters hibernate", 15
PLAY "MF": PLAY "MBL8C+L16E-L8F.F+FC+"
LYRIC "Under the snow and ice", 15
PLAY "MF": PLAY "MBL8FG+G+G+G+L4G+L8FL4G+"
LYRIC "We wake up all the sleepyheads", 14
PLAY "MF": PLAY "MBL16C+L8E-.FF+FL4C+P8"
LYRIC "So quietly and nice", 14
PLAY "MF": PLAY "MBL16C+L8E-F.E-L16C+L8E-F.L4C+"
LYRIC "We help them gather up their food", 15
PLAY "MF": PLAY "MBL8F+F+F+L16F+L4G+P8P16"
LYRIC "Fix their homes below", 15
PLAY "MF": PLAY "MBL16C+L8E-F.E-L16C+L8E-F.L4FP8"
LYRIC "We welcome back the southern birds", 14
PLAY "MF": PLAY "MBL16C+C+L8G+L16G+L8G+.L4B-MLL4G+.MNL2G+"
LYRIC "So their families can grow", 14
'Twi:
'PLAY "T112"
BIGLINE 2
LYRIC "CHORUS", 7
BIGLINE 3

COLOR 7
PRINT "             º ";
COLOR 10
PLAY "MF"
PRINT "Win";
'PLAY "T116L8C+C+FC+F+F+B-G+"
PLAY "T116MLL64<G+>C+<G+>C+<G+>C+<G+P64"
PRINT "ter ";
PLAY "G+>C+<G+>C+<G+>C+<G+P64"
PRINT "Wrap-";
PLAY ">C+FC+FC+FC+<P64"
PRINT "Up";
PLAY "G+>C+<G+>C+<G+>C+<G+P64"
COLOR 7
PRINT "                                      º "
PRINT "             º ";
COLOR 10
'LYRIC "Winter Wrap-Up", 10
PRINT "Win";
PLAY ">C+F+C+F+C+F+C+P64"
PRINT "ter ";
PLAY "C+F+C+F+C+F+C+P64"
PRINT "Wrap-";
PLAY "F+B-F+B-F+B-F+P64"
PRINT "Up";
PLAY "E-G+E-G+E-G+P64P8"
'LYRIC "Winter Wrap-Up", 10
COLOR 7
PRINT "                                      º "
PLAY "MBMNL8G+L16G+G+L8FG+L16FL8E-.C+"
LYRIC "Let's finish our holiday cheer", 10
COLOR 7
PRINT "             º ";
COLOR 10
PLAY "MF"
PRINT "Win";
'PLAY "T116L8C+C+FC+F+F+B-G+"
PLAY "T116MLL64<G+>C+<G+>C+<G+>C+<G+P64"
PRINT "ter ";
PLAY "G+>C+<G+>C+<G+>C+<G+P64"
PRINT "Wrap-";
PLAY ">C+FC+FC+FC+<P64"
PRINT "Up";
PLAY "G+>C+<G+>C+<G+>C+<G+P64"
COLOR 7
PRINT "                                      º "
PRINT "             º ";
COLOR 10
'LYRIC "Winter Wrap-Up", 10
PRINT "Win";
PLAY ">C+F+C+F+C+F+C+P64"
PRINT "ter ";
PLAY "C+F+C+F+C+F+C+P64"
PRINT "Wrap-";
PLAY "F+B-F+B-F+B-F+P64"
PRINT "Up";
PLAY "E-G+E-G+E-G+P64P8"
'LYRIC "Winter Wrap-Up", 10
COLOR 7
PRINT "                                      º "
PLAY "MBMNL16G+G+L8G+FG+L4B-L8G+"
LYRIC "'Cause tomorrow spring is here", 10
COLOR 7
PRINT "             º ";
COLOR 10
PLAY "MF"
PRINT "Win";
'PLAY "T116L8C+C+FC+F+F+B-G+"
PLAY "T116MLL64<G+>C+<G+>C+<G+>C+<G+P64"
PRINT "ter ";
PLAY "G+>C+<G+>C+<G+>C+<G+P64"
PRINT "Wrap-";
PLAY ">C+FC+FC+FC+<P64"
PRINT "Up";
PLAY "G+>C+<G+>C+<G+>C+<G+P64"
COLOR 7
PRINT "                                      º "
PRINT "             º ";
COLOR 10
'LYRIC "Winter Wrap-Up", 10
PRINT "Win";
PLAY ">C+F+C+F+C+F+C+P64"
PRINT "ter ";
PLAY "C+F+C+F+C+F+C+P64"
PRINT "Wrap-";
PLAY "F+B-F+B-F+B-F+P64"
PRINT "Up";
PLAY "E-G+E-G+E-G+P64P8"
'LYRIC "Winter Wrap-Up", 10
COLOR 7
PRINT "                                      º "
PLAY "MBMNL16G+G+L8G+FG+L4B-G+"
LYRIC "'Cause tomorrow spring is here", 10
PLAY "MBMNL16G+G+L8G+FG+FL4C+"
LYRIC "'Cause tomorrow spring is here", 10

BIGLINE 2
LYRIC "BRIDGE 1", 7
BIGLINE 3


PLAY "T112"
PLAY "MFP8": PLAY "MBL8FFFE-L16C+L8E-FMLL4C+MNL16C+"
LYRIC "No easy task to clear the ground", 6
PLAY "MF": PLAY "MBL16E-L8FF+FE-MLL4C+MNL16C+"
LYRIC "Plant our tiny seeds", 6
PLAY "MF": PLAY "MBL8FFFG+.E-FMLL4C+MNL16C+"
LYRIC "With proper care and sunshine", 6
PLAY "MF": PLAY "MBL8FFL16E-L8C+MLL4C+MNL16C+"
LYRIC "Everyone it feeds", 6
PLAY "MF": PLAY "MBL8CFFCL16F+FFMLL4C+MNL16C+"
LYRIC "Apples, carrots, celery stalks", 6
PLAY "MF": PLAY "MBL16G+G+L8G+G+B-L2G+"
LYRIC "Colorful flowers too", 6
PLAY "MF": PLAY "MBL8CFFC+L16F+L8FC+."
LYRIC "We must work so very hard", 6
PLAY "MF": PLAY "MBG+B-G+G+L16FL2G+"
LYRIC "It's just so much to do", 6

BIGLINE 2
LYRIC "CHORUS", 7
BIGLINE 3

COLOR 7
PRINT "             º ";
COLOR 10
PLAY "MF"
PRINT "Win";
'PLAY "T116L8C+C+FC+F+F+B-G+"
PLAY "T116MLL64<G+>C+<G+>C+<G+>C+<G+P64"
PRINT "ter ";
PLAY "G+>C+<G+>C+<G+>C+<G+P64"
PRINT "Wrap-";
PLAY ">C+FC+FC+FC+<P64"
PRINT "Up";
PLAY "G+>C+<G+>C+<G+>C+<G+P64"
COLOR 7
PRINT "                                      º "
PRINT "             º ";
COLOR 10
'LYRIC "Winter Wrap-Up", 10
PRINT "Win";
PLAY ">C+F+C+F+C+F+C+P64"
PRINT "ter ";
PLAY "C+F+C+F+C+F+C+P64"
PRINT "Wrap-";
PLAY "F+B-F+B-F+B-F+P64"
PRINT "Up";
PLAY "E-G+E-G+E-G+P64P8"
'LYRIC "Winter Wrap-Up", 10
COLOR 7
PRINT "                                      º "
PLAY "MBMNL8G+L16G+G+L8FG+L16FL8E-.C+"
LYRIC "Let's finish our holiday cheer", 10
COLOR 7
PRINT "             º ";
COLOR 10
PLAY "MF"
PRINT "Win";
'PLAY "T116L8C+C+FC+F+F+B-G+"
PLAY "T116MLL64<G+>C+<G+>C+<G+>C+<G+P64"
PRINT "ter ";
PLAY "G+>C+<G+>C+<G+>C+<G+P64"
PRINT "Wrap-";
PLAY ">C+FC+FC+FC+<P64"
PRINT "Up";
PLAY "G+>C+<G+>C+<G+>C+<G+P64"
COLOR 7
PRINT "                                      º "
PRINT "             º ";
COLOR 10
'LYRIC "Winter Wrap-Up", 10
PRINT "Win";
PLAY ">C+F+C+F+C+F+C+P64"
PRINT "ter ";
PLAY "C+F+C+F+C+F+C+P64"
PRINT "Wrap-";
PLAY "F+B-F+B-F+B-F+P64"
PRINT "Up";
PLAY "E-G+E-G+E-G+P64P8"
'LYRIC "Winter Wrap-Up", 10
COLOR 7
PRINT "                                      º "
PLAY "MBMNL16G+G+L8G+FG+L4B-L8G+"
LYRIC "'Cause tomorrow spring is here", 10
COLOR 7
PRINT "             º ";
COLOR 10
PLAY "MF"
PRINT "Win";
'PLAY "T116L8C+C+FC+F+F+B-G+"
PLAY "T116MLL64<G+>C+<G+>C+<G+>C+<G+P64"
PRINT "ter ";
PLAY "G+>C+<G+>C+<G+>C+<G+P64"
PRINT "Wrap-";
PLAY ">C+FC+FC+FC+<P64"
PRINT "Up";
PLAY "G+>C+<G+>C+<G+>C+<G+P64"
COLOR 7
PRINT "                                      º "
PRINT "             º ";
COLOR 10
'LYRIC "Winter Wrap-Up", 10
PRINT "Win";
PLAY ">C+F+C+F+C+F+C+P64"
PRINT "ter ";
PLAY "C+F+C+F+C+F+C+P64"
PRINT "Wrap-";
PLAY "F+B-F+B-F+B-F+P64"
PRINT "Up";
PLAY "E-G+E-G+E-G+P64P8"
'LYRIC "Winter Wrap-Up", 10
COLOR 7
PRINT "                                      º "
PLAY "MBMNL16G+G+L8G+FG+L4B-G+"
LYRIC "'Cause tomorrow spring is here", 13
PLAY "L16G+G+L8G+FG+FL4C+"
LYRIC "'Cause tomorrow spring is here", 10

BIGLINE 2
LYRIC "BRIDGE 2", 7
BIGLINE 3

PLAY "MFT96P8": PLAY "MBL8C+L16E-L8F.E-C+L16E-L8F.C+"
LYRIC "Now that I know what they all do", 5
PLAY "MF": PLAY "MBF+F+L16F+L8F+G+.L4G+P8"
LYRIC "I have to find my place", 5
PLAY "MF": PLAY "MBL8C+E-FF+FL16E-L8F.C+"
LYRIC "And help with all of my heart", 5
PLAY "MF": PLAY "MBF+F+L16FF+L8FL2C+"
LYRIC "Tough task ahead I face", 5
PLAY "MF": PLAY "MBL16C+L8E-F.FL16C+L8C+F.F"
LYRIC "How will I do without my magic?", 5
PLAY "MF": PLAY "MBC+F+L16FL8F+.FG+L4G+"
LYRIC "Help the earth pony way?", 5
PLAY "MF": PLAY "MBL8>C+L16C+C+<B->L8C+.<B->E-.L4C+P16"
LYRIC "I wanna belong, so I must", 5
PLAY "MF": PLAY "MBL8C+L16<B->L8C+E-.MLL4C+T106MNC+"
LYRIC "Do my best today", 5
PLAY "MF": PLAY "MBL8C+.<B->C+L16MLE-MNL4E-<"
LYRIC "Do my best today", 5

BIGLINE 2
LYRIC "CHORUS", 7
BIGLINE 3
Twi:
COLOR 7
PRINT "             º ";
COLOR 10
PLAY "MF"
PRINT "Win";
'PLAY "T116L8C+C+FC+F+F+B-G+"
PLAY "T116MLL64<G+>C+<G+>C+<G+>C+<G+P64"
PRINT "ter ";
PLAY "G+>C+<G+>C+<G+>C+<G+P64"
PRINT "Wrap-";
PLAY ">C+FC+FC+FC+<P64"
PRINT "Up";
PLAY "G+>C+<G+>C+<G+>C+<G+P64"
COLOR 7
PRINT "                                      º "
PRINT "             º ";
COLOR 10
'LYRIC "Winter Wrap-Up", 10
PRINT "Win";
PLAY ">C+F+C+F+C+F+C+P64"
PRINT "ter ";
PLAY "C+F+C+F+C+F+C+P64"
PRINT "Wrap-";
PLAY "F+B-F+B-F+B-F+P64"
PRINT "Up";
PLAY "E-G+E-G+E-G+P64P8"
'LYRIC "Winter Wrap-Up", 10
COLOR 7
PRINT "                                      º "
PLAY "MBMNL8G+L16G+G+L8FG+L16FL8E-.C+"
LYRIC "Let's finish our holiday cheer", 10
COLOR 7
PRINT "             º ";
COLOR 10
PLAY "MF"
PRINT "Win";
'PLAY "T116L8C+C+FC+F+F+B-G+"
PLAY "T116MLL64<G+>C+<G+>C+<G+>C+<G+P64"
PRINT "ter ";
PLAY "G+>C+<G+>C+<G+>C+<G+P64"
PRINT "Wrap-";
PLAY ">C+FC+FC+FC+<P64"
PRINT "Up";
PLAY "G+>C+<G+>C+<G+>C+<G+P64"
COLOR 7
PRINT "                                      º "
PRINT "             º ";
COLOR 10
'LYRIC "Winter Wrap-Up", 10
PRINT "Win";
PLAY ">C+F+C+F+C+F+C+P64"
PRINT "ter ";
PLAY "C+F+C+F+C+F+C+P64"
PRINT "Wrap-";
PLAY "F+B-F+B-F+B-F+P64"
PRINT "Up";
PLAY "E-G+E-G+E-G+P64P8"
'LYRIC "Winter Wrap-Up", 10
COLOR 7
PRINT "                                      º "
PLAY "MBMNL16G+G+L8G+FG+L4B-L8G+"
LYRIC "'Cause tomorrow spring is here", 10
COLOR 7
PRINT "             º ";
COLOR 10
PLAY "MF"
PRINT "Win";
'PLAY "T116L8C+C+FC+F+F+B-G+"
PLAY "T116MLL64<G+>C+<G+>C+<G+>C+<G+P64"
PRINT "ter ";
PLAY "G+>C+<G+>C+<G+>C+<G+P64"
PRINT "Wrap-";
PLAY ">C+FC+FC+FC+<P64"
PRINT "Up";
PLAY "G+>C+<G+>C+<G+>C+<G+P64"
COLOR 7
PRINT "                                      º "
PRINT "             º ";
COLOR 10
'LYRIC "Winter Wrap-Up", 10
PRINT "Win";
PLAY ">C+F+C+F+C+F+C+P64"
PRINT "ter ";
PLAY "C+F+C+F+C+F+C+P64"
PRINT "Wrap-";
PLAY "F+B-F+B-F+B-F+P64"
PRINT "Up";
PLAY "E-G+E-G+E-G+P64P8"
'LYRIC "Winter Wrap-Up", 10
COLOR 7
PRINT "                                      º "
PLAY "MBMNL16G+G+L8G+FG+L4B-G+"
LYRIC "'Cause tomorrow spring is here", 5
PLAY "MBMNL16G+G+L8G+FF+L4FE-"
LYRIC "'Cause tomorrow spring is here", 5
PLAY "MBMNL16G+G+L8G+FG+>L4CL1C+"
LYRIC "'Cause tomorrow spring is here", 5
PLAY "P8P1"
'PLAY "MBMNL16O2G+G+FL8G+.G+L16G+L8F+G+.G+L16G+"

BIGLINE 2
LYRIC "'Winter Wrap-Up' in MS-DOS QBASIC", 7
LYRIC "By Cat333Pok‚mon", 7
LYRIC "April 26, 2012", 7
LYRIC "Original composed by Daniel Ingram", 7
PLAY "O2L64MLFG+FG+FG+FG+FG+FG+FG+FG+FG+FG+FG+FG+FG+FG+FG+FG+"
PLAY "E-G+E-G+E-G+E-G+E-G+E-G+E-G+E-G+E-G+E-G+E-G+E-G+E-G+E-G+E-G+E-G+"
PLAY "C+FG+C+FG+C+FG+C+FG+C+FG+C+FG+C+FG+C+FG+C+FG+C+FG+C+FG+C+FG+C+FG+C+FG+C+FG+C+FG+C+FG+C+FG+C+FG+C+FG+C+FG+C+FG+C+FG+C+FG+C+FG+C+FG+C+FG+C+FG+C+FG+C+FG+C+FG+C+FG+C+FG+"
BIGLINE 4

END

SUB BIGLINE (ENDTYPE AS INTEGER)
COLOR 7
PRINT "             ";
IF ENDTYPE = 1 THEN
        PRINT "É";
ELSEIF ENDTYPE = 2 THEN
        PRINT "Ì";
ELSEIF ENDTYPE = 3 THEN
        PRINT "Ç";
ELSEIF ENDTYPE = 4 THEN
        PRINT "È";
END IF
IF ENDTYPE = 3 THEN
        PRINT "ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ";
ELSE
        PRINT "ÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍ";
END IF
IF ENDTYPE = 1 THEN
        PRINT "»"
ELSEIF ENDTYPE = 2 THEN
        PRINT "¹"
ELSEIF ENDTYPE = 3 THEN
        PRINT "¶"
ELSEIF ENDTYPE = 4 THEN
        PRINT "¼"
END IF
END SUB

SUB LYRIC (VAR AS STRING, VARCOLOR AS INTEGER)
DIM i AS INTEGER
DIM timeC AS DOUBLE
i = LEN(VAR)

COLOR 7
PRINT "             º ";
COLOR VARCOLOR
'PRINT VAR;
FOR k = 1 TO LEN(VAR)
    PRINT MID$(VAR, k, 1);
    timeC = TIMER
    DO
    LOOP UNTIL TIMER <> timeC
NEXT k
FOR j = 0 TO (50 - i)
    PRINT " ";
NEXT j
COLOR 7
PRINT " º"

IF LEN(VAR) > 10 THEN
    DO UNTIL PLAY(0) = 0
        'Delay
    LOOP
END IF

END SUB

